/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico1;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Harold
 */
public class Lienzo extends javax.swing.JPanel implements Runnable {

    int x =0 ;
    int y = 0;
    int wOval = 40;
    int hOval = 40;
    int wRect = 50;
    int hRect = 80;
    int xRect ;
    Thread hilo;
    
    public Lienzo() {
        initComponents();
        hilo =  new Thread(this);
        
    }
    
    public void paint(Graphics g){
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.black);
        g.drawLine(getWidth()/2,0,getWidth()/2,getHeight());
        g.setColor(Color.blue);
        g.fillOval(x, y, wOval, hOval);
        g.drawRect( getWidth()/2 - wRect/2, getHeight()-hRect, wRect, hRect );
        //linea del medio eje x
        
      //  g.drawRect( getWidth()/2-wRect/2, getHeight()-hRect, wRect, hRect );
        
        System.out.println("x = " + x );
        System.out.println("y =" + y);
    }
    
    
    public void inicio(){
        hilo.start();
    }
    
    public void pausa(){
        hilo.suspend();
    }
    
    public void  continuar(){
        hilo.resume();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        y = getHeight()-hOval;
        xRect = getWidth()/2;
        System.out.println("valor en run de y :  " + y);
        try{
          while(true){
              //recorre eje x de izd a drcha
                while(x<=getWidth()-wOval ){
                  
                  
                    while(x>=getWidth()/2 - wRect/2 - wOval && y<= getHeight()-hOval  && x<= getWidth()/2 - wRect/2){
                        if(y<=getHeight()-hRect-hOval){
                            break;
                        }
                        Thread.sleep(100);
                        y -= 10;
                        repaint();
                    }

                    while(y<=getHeight()-hRect-hOval &&  x>= getWidth()/2 - wRect/2 - wOval &&  x<= getWidth()/2 + wRect/2){
                          
                          if(x>= getWidth()/2 + wRect/2){
                              break;
                          }
                          Thread.sleep(100);
                          x += 10;
                          repaint();
                    }
                        
                    while(x>= getWidth()/2 + wRect/2 && y<= getHeight() - hOval){
         
                                if(y >= getHeight()- hOval){
                                    break;
                                }
                                Thread.sleep(100);
                                y += 10;
                                repaint();
                                /*if(x>= getWidth()/2 + wRect/2){
                                    break;
                                }*/
                                
                    }
                    
                    if(x>= getWidth()-wOval ){
                        break;
                    }
                  Thread.sleep(50);
                  x += 10;
                  repaint();
                  
                }
              
              
              
              // recorre eje y de abajo a arriba 
              while(y>0){
                  Thread.sleep(50);
                  y -= 10;
                  repaint();
                  
              }
              
              //recorre eje x de drcha a izq
              while(x>0){
                  Thread.sleep(50);
                  x -= 10;
                  repaint();
              }
              //recorre eje y de arriba a abajo
              while(y<getHeight()-wOval){
                  Thread.sleep(50);
                  y += 10;
                  repaint();
              }
          }  
        }catch(Exception e){
            System.out.println(e);
        }
    }
}
